#!/usr/bin/env bash
THEME='Fluent-dark'
ICONS='Adwaita'
CURSOR='macOSBigSur'
FONT='PingFang SC 9'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes () {
        ${SCHEMA} gtk-theme     "$THEME"
        ${SCHEMA} icon-theme    "$ICONS"
        ${SCHEMA} cursor-theme  "$CURSOR"
        ${SCHEMA} font-name     "$FONT"
    }

apply_themes
